---
- block:

  - name: Install dnsmasq
    yum:
      name: dnsmasq
      state: installed

  - name: Render the config
    template:
      src: "dnsmasq.conf.j2"
      dest: "/etc/dnsmasq.conf"
      backup: yes
    register: dnsmasq_conf_result

  - name: Write the hosts file
    template:
      src: "dnsmasq.hosts.j2"
      dest: "/etc/dnsmasq.hosts"
      backup: yes
    register: dnsmasq_hosts_result

  - name: Restart dnsmasq when the configs change
    systemd:
      name: dnsmasq.service
      state: restarted
    when: dnsmasq_conf_result is changed or dnsmasq_hosts_result is changed

  - name: Start and Enable dnsmasq
    systemd:
      name: dnsmasq.service
      state: started
      enabled: True
  
  - name: Open firewall ports
    firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      zone: "{{ dnsmasq_firewalld_zone }}"
      state: enabled
    with_items:
      - dhcp
      - dns

  become: True
